disable-version-check: false
log-level: info
report:
    format: json
    no-color: false
    output: "./scan_results/bearer.out.json"
    report: security
    severity: critical,high
rule:
    disable-default-rules: false
    only-rule: []
    skip-rule: []
scan:
    context: ""
    data_subject_mapping: ""
    disable-domain-resolution: true
    domain-resolution-timeout: 3s
    external-rule-dir: []
    force: false
    hide_progress_bar: false
    internal-domains: []
    parallel: 0
    quiet: true
    exit-code: 0
    scanner:
        - secrets
        - sast
    skip-test: true
    skip-path: ['*/vendor']
